package Vista.Descuentos;

import Controller.FuncionesDescuentos;
import Vista.Notificaciones.Aceptar_Cancelar;
import Vista.Notificaciones.Advertencia;
import Vista.Notificaciones.Fallo;
import Vista.Notificaciones.Realizado;
import View.Principal3;
import java.awt.Color;
import java.awt.Frame;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SwichBlade15
 */
public final class SeleccionarDescuentos extends javax.swing.JDialog {

    FuncionesDescuentos funcion = new FuncionesDescuentos();

    public SeleccionarDescuentos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getRootPane().setOpaque(false);
        this.getContentPane().setBackground(new Color(0, 0, 0, 0));
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);

        this.setLocationRelativeTo(null);
        rbtnClientes.doClick();
    }

    //Mostrar clientes por codigo
    public void mostrarClientesCodigo(String codigo) {
        try {
            DefaultTableModel modelo;
            modelo = funcion.mostrarClientesDescuentosCedula(codigo);
            tblDescuentos.setModel(modelo);
//            ocultar_columnas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    //Mostrar clientes por nombre
    public void mostrarClientesNombre(String nombre) {
        try {
            DefaultTableModel modelo;
            modelo = funcion.mostrarClientesDescuentosNombre(nombre);
            tblDescuentos.setModel(modelo);
//            ocultar_columnas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
//********************FIN MOSTRAR CLIENTES**********************//

//********************MOSTRAR CATEGORIAS**********************//
    public void mostrarCategoriasCodigo(String codigo) {
        try {
            DefaultTableModel modelo;
            modelo = funcion.mostrarCategoriasDescuentosCodigo(codigo);
            tblDescuentos.setModel(modelo);
//            ocultar_columnas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void mostrarCategoriasNombre(String nombre) {
        try {
            DefaultTableModel modelo;
            modelo = funcion.mostrarCategoriasDescuentosNombre(nombre);
            tblDescuentos.setModel(modelo);
//            ocultar_columnas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
//********************FIN MOSTRAR CATEGORIAS**********************//    

//********************MOSTRAR PRODUCTOS**********************//
    //Mostrar productos por codigo
    public void mostrarProductosCodigo(String codigo) {
        try {
            DefaultTableModel modelo;
            modelo = funcion.mostrarProductosDescuentosCodigo(codigo);
            tblDescuentos.setModel(modelo);
//            ocultar_columnas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    //Mostrar productos por nombre
    public void mostrarProductosNombre(String nombre) {
        try {
            DefaultTableModel modelo;
            modelo = funcion.mostrarProductosDescuentosNombre(nombre);
            tblDescuentos.setModel(modelo);
//            ocultar_columnas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
//********************FIN MOSTRAR PRODUCTOS**********************//

//    public void ocultar_columnas() {
//        tblDescuentos.getColumnModel().getColumn(0).setMaxWidth(0);
//        tblDescuentos.getColumnModel().getColumn(0).setMinWidth(0);
//        tblDescuentos.getColumnModel().getColumn(0).setPreferredWidth(0);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtngDescuentos = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDescuentos = new javax.swing.JTable();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rbtnClientes = new javax.swing.JRadioButton();
        rbtnCategorias = new javax.swing.JRadioButton();
        rbtnProductos = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccionar Descuentos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 390, -1));

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar32.png"))); // NOI18N
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 14, 40, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDescuentos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        tblDescuentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblDescuentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDescuentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDescuentos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 410, 152));

        txtCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoFocusGained(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
        });
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Codigo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreFocusGained(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 300, -1));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 430, 220));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbtnClientes.setBackground(new java.awt.Color(255, 255, 255));
        rbtngDescuentos.add(rbtnClientes);
        rbtnClientes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbtnClientes.setText("Clientes");
        rbtnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnClientesActionPerformed(evt);
            }
        });
        jPanel2.add(rbtnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 14, -1, -1));

        rbtnCategorias.setBackground(new java.awt.Color(255, 255, 255));
        rbtngDescuentos.add(rbtnCategorias);
        rbtnCategorias.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbtnCategorias.setText("Categorias");
        rbtnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCategoriasActionPerformed(evt);
            }
        });
        jPanel2.add(rbtnCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 14, -1, -1));

        rbtnProductos.setBackground(new java.awt.Color(255, 255, 255));
        rbtngDescuentos.add(rbtnProductos);
        rbtnProductos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbtnProductos.setText("Productos");
        rbtnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnProductosActionPerformed(evt);
            }
        });
        jPanel2.add(rbtnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 14, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPanelDescuentos1.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoSeleccionarDescuentos.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnClientesActionPerformed
        mostrarClientesCodigo("");
    }//GEN-LAST:event_rbtnClientesActionPerformed

    private void rbtnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCategoriasActionPerformed
        mostrarCategoriasCodigo("");
    }//GEN-LAST:event_rbtnCategoriasActionPerformed

    private void rbtnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnProductosActionPerformed
        mostrarProductosCodigo("");
    }//GEN-LAST:event_rbtnProductosActionPerformed

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased
        if (rbtnClientes.isSelected()) {
            mostrarClientesCodigo(txtCodigo.getText());
        } else if (rbtnCategorias.isSelected()) {
            mostrarCategoriasCodigo(txtCodigo.getText());
        } else if (rbtnProductos.isSelected()) {
            mostrarProductosCodigo(txtCodigo.getText());
        }
    }//GEN-LAST:event_txtCodigoKeyReleased

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        if (rbtnClientes.isSelected()) {
            mostrarClientesNombre(txtNombre.getText());
        } else if (rbtnCategorias.isSelected()) {
            mostrarCategoriasNombre(txtNombre.getText());
        } else if (rbtnProductos.isSelected()) {
            mostrarProductosNombre(txtNombre.getText());
        }
    }//GEN-LAST:event_txtNombreKeyReleased

    private void tblDescuentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDescuentosMouseClicked
        int seleccionar = tblDescuentos.rowAtPoint(evt.getPoint());

        if (evt.getClickCount() == 2) {
            Descuentos.txtIddetalledescuentos.setText(String.valueOf(tblDescuentos.getValueAt(seleccionar, 0)));
            Descuentos.txtAplicar.setText(String.valueOf(tblDescuentos.getValueAt(seleccionar, 1)));
            Descuentos.txtCodigo.setText(String.valueOf(tblDescuentos.getValueAt(seleccionar, 2)));

            if (rbtnClientes.isSelected()) {
                Descuentos.txtTipo.setText("Clientes");
                Descuentos.txtCantidad.setEditable(false);
            } else if (rbtnCategorias.isSelected()) {
                Descuentos.txtTipo.setText("Categorias");
                Descuentos.txtCantidad.setEditable(false);
            } else if (rbtnProductos.isSelected()) {
                Descuentos.txtTipo.setText("Productos");
                Descuentos.txtCantidad.setEditable(true);
            }
            
            Descuentos.txtCantidad.setText("0");
            Descuentos.txtCantidad.setBackground(Color.white);

            dispose();
        }
    }//GEN-LAST:event_tblDescuentosMouseClicked

    private void txtCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusGained
        txtCodigo.setText("");
        txtNombre.setText("");
    }//GEN-LAST:event_txtCodigoFocusGained

    private void txtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusGained
        txtCodigo.setText("");
        txtNombre.setText("");
    }//GEN-LAST:event_txtNombreFocusGained

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        Principal3.lblProceso.setText("Proceso: OFF");
        this.dispose();
    }//GEN-LAST:event_lblCerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarDescuentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            SeleccionarDescuentos dialog = new SeleccionarDescuentos(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    //Metodos para llamar a los JDialog de Advertencia, Fallo y Realizado
    Frame f = JOptionPane.getFrameForComponent(this);
    String mensaje;
    String encabezado;
    Icon icono;

    public void advertencia() {
        Advertencia dialog = new Advertencia(f, true);
        Advertencia.lblEncabezado.setText(mensaje);
        dialog.setVisible(true);
    }

    public void fallo() {
        Fallo dialog = new Fallo(f, true);
        Fallo.lblEncabezado.setText(mensaje);
        dialog.setVisible(true);
    }

    public void realizado() {
        Realizado dialog = new Realizado(f, true);
        Realizado.lblEncabezado.setText(mensaje);
        dialog.setVisible(true);
    }

    public void aceptarCancelar() {
        Aceptar_Cancelar dialog = new Aceptar_Cancelar(f, true);
        icono = new ImageIcon(getClass().getResource("/Imagenes/FondoCerrarSesion.png"));
        Aceptar_Cancelar.lblFondo.setIcon(icono);
        Aceptar_Cancelar.lblEncabezado.setText(encabezado);
        Aceptar_Cancelar.lblMensaje.setText(mensaje);
        dialog.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JRadioButton rbtnCategorias;
    private javax.swing.JRadioButton rbtnClientes;
    private javax.swing.JRadioButton rbtnProductos;
    private javax.swing.ButtonGroup rbtngDescuentos;
    private javax.swing.JTable tblDescuentos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
