package Vista.Otros;

import Vista.Notificaciones.Aceptar_Cancelar;
import Vista.Notificaciones.Advertencia;
import Vista.Notificaciones.Fallo;
import Vista.Notificaciones.Realizado;
import java.awt.Frame;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author SwichBlade15
 */
public class CodeBar extends javax.swing.JInternalFrame {


    public CodeBar() {
        initComponents();
    }

//    private void codigo() {
//        Barcode128 codigo128 = new Barcode128();
//        codigo128.setCode(txtCodigo.getText());
//        Image img = codigo128.createAwtImage(Color.BLACK, Color.WHITE);
//
//        BufferedImage bImage = new BufferedImage(img.getWidth(null), img.getHeight(null), BufferedImage.TYPE_INT_RGB);
//        Graphics2D g = bImage.createGraphics();
//        g.drawImage(img, 0, 0, null);
//        g.dispose();
//
//        final String rutaImagen = "src/Imagenes/";
//        Path rutarelativaImagen = Paths.get(rutaImagen);
//
//        Path rutaabsolutaImagen = rutarelativaImagen.toAbsolutePath();
//        String rutaImagen1 = rutaabsolutaImagen.toString();
//
//        try {
//            ImageIO.write(bImage, "jpg", new File(rutaImagen1 + "code128.jpg"));
//        } catch (IOException ex) {
//            Logger.getLogger(CodeBar.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//        JasperReport reporte;
//        Map<String, Object> map = new HashMap<String, Object>();
//        map.put("codigo", txtCodigo.getText());
//        map.put("imagen", rutaImagen1 + "code128.jpg");
//        
//        try {
//
//            final String ruta = "src/Reportes/CodeBar.jrxml";
//            Path rutarelativa = Paths.get(ruta);
//            System.out.println("Ruta relativa: " + rutarelativa);
//
//            Path rutaabsoluta = rutarelativa.toAbsolutePath();
//            System.out.println("Ruta Absoluta: " + rutaabsoluta);
//            String ruta1 = rutaabsoluta.toString();
//
//            reporte = JasperCompileManager.compileReport(ruta1);
//
//            JasperPrint jp = JasperFillManager.fillReport(reporte, map, new JREmptyDataSource());
//            JasperViewer view = new JasperViewer(jp, false);
//            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//            view.setVisible(true);
//        } catch (JRException e) {
//            JOptionPane.showMessageDialog(null, e);
//            mensaje = "Error al generar reporte";
//            fallo();
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CodeBar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Codigo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 186, -1));

        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel3.setText("Generar código de barras en Code-128");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, -1, -1));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        codigo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
//        codigo();
    }//GEN-LAST:event_txtCodigoActionPerformed

    //Metodos para llamar a los JDialog de Advertencia, Fallo y Realizado
    Frame f = JOptionPane.getFrameForComponent(this);
    String mensaje;
    String encabezado;
    Icon icono;

    public void advertencia() {
        Advertencia dialog = new Advertencia(f, true);
        Advertencia.lblEncabezado.setText(mensaje);
        dialog.setVisible(true);
    }

    public void fallo() {
        Fallo dialog = new Fallo(f, true);
        Fallo.lblEncabezado.setText(mensaje);
        dialog.setVisible(true);
    }

    public void realizado() {
        Realizado dialog = new Realizado(f, true);
        Realizado.lblEncabezado.setText(mensaje);
        dialog.setVisible(true);
    }

    public void aceptarCancelar() {
        Aceptar_Cancelar dialog = new Aceptar_Cancelar(f, true);
        icono = new ImageIcon(getClass().getResource("/Imagenes/FondoNotificacionesAzul.png"));
        Aceptar_Cancelar.lblFondo.setIcon(icono);
        Aceptar_Cancelar.lblEncabezado.setText(encabezado);
        Aceptar_Cancelar.lblMensaje.setText(mensaje);
        dialog.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
