package Vista.Notificaciones;

import Utils.ControlCantidad;
import Utils.Vencimientos;
import View.Principal3;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import Utils.VencimientosGastos;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SwichBlade15
 */
public class Notificaciones extends javax.swing.JInternalFrame {

    ControlCantidad control = new ControlCantidad();
    Vencimientos vencimientos = new Vencimientos();
    VencimientosGastos vencimientogastos = new VencimientosGastos();
    DefaultTableModel modelo;
    JPanel pnlNot = new JPanel();
    private final List<JLabel> label;
    private int i;
    private final int indice = 0;

    public Notificaciones() {
        initComponents();
        scroll.getViewport().setBackground(Color.yellow);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setBackground(new Color(0, 0, 0, 0));
        this.setIconifiable(false);
        this.setBorder(null);

//        pnlNot.addMouseListener(new java.awt.event.MouseAdapter() {
//            @Override
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                notificaciones();
//            }
//        });

        label = new ArrayList<>();
    }

    public void notificaciones() {
        System.out.println("Entro notificaciones");
        if (Principal3.tblNotificaciones.getRowCount() > 0) {
            System.out.println(Principal3.tblNotificaciones.getRowCount());
            System.out.println("Entro if");
            for (i = 0; i < Principal3.tblNotificaciones.getRowCount(); i++) {
                System.out.println("Entro for: "+i+" Veces");
                pnlNot.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
                getContentPane().add(pnlNot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 826, 66));
                pnlNot.setBackground(Color.WHITE);

                JLabel lblFondoNot = new JLabel("", indice);
                Icon icon = new ImageIcon(getClass().getResource("/Imagenes/FondoNotificacionesEmergentes4Gris.png"));
                lblFondoNot.setIcon(icon);
                lblFondoNot.setPreferredSize(new Dimension(826, 66));

                JLabel datos = new JLabel(String.valueOf(Principal3.tblNotificaciones.getValueAt(i, 1))+ " " + String.valueOf(Principal3.tblNotificaciones.getValueAt(i, 2)), indice);
                System.out.println("Datos: "+datos.getText());
                pnlNot.add(datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, 826, 67));
                pnlNot.add(lblFondoNot, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, 826, 67));

                label.add(lblFondoNot);
                pnlNotificaciones.add(pnlNot);
                System.out.println("Agrego panel notificaciones");
                pnlNotificaciones.updateUI();   
                System.out.println("Actualizo panel notificaciones");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEncabezado = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        btnNotificacionesOculto = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        pnlNotificaciones = new javax.swing.JPanel();
        lblFondo = new javax.swing.JLabel();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEncabezado.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        lblEncabezado.setForeground(new java.awt.Color(255, 255, 255));
        lblEncabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEncabezado.setText("Notificaciones");
        getContentPane().add(lblEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 280, -1));

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar32.png"))); // NOI18N
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 14, -1, -1));

        btnNotificacionesOculto.setText("NotificacionesOculto");
        btnNotificacionesOculto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificacionesOcultoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNotificacionesOculto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        scroll.setBackground(new java.awt.Color(255, 255, 255));
        scroll.setBorder(null);
        scroll.setForeground(new java.awt.Color(255, 255, 255));
        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlNotificaciones.setBackground(new java.awt.Color(255, 255, 255));
        pnlNotificaciones.setLayout(new java.awt.GridLayout(0, 3));
        scroll.setViewportView(pnlNotificaciones);

        getContentPane().add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 900, 470));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNotificaciones.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        Principal3.lblProceso.setText("Proceso: OFF");
        this.dispose();
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void btnNotificacionesOcultoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificacionesOcultoActionPerformed
        System.out.println("Boton de notificaciones oculto");
        notificaciones();
    }//GEN-LAST:event_btnNotificacionesOcultoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnNotificacionesOculto;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblEncabezado;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JPanel pnlNotificaciones;
    public static javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
