package View.Caja;

import Config.DataSource;
import Model.DatosCaja;
import Model.DatosDetalleCaja;
import Controller.FuncionesCaja;
import Controller.FuncionesAuditoria;
import Vista.Notificaciones.Advertencia;
import Vista.Notificaciones.Fallo;
import Vista.Notificaciones.Realizado;
import View.Principal3;
import java.awt.Color;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SwichBlade15
 */
public final class AperturaCaja extends javax.swing.JInternalFrame {

    FuncionesCaja funcion = new FuncionesCaja();
    DatosCaja datos = new DatosCaja();
    DatosDetalleCaja datosdetalle = new DatosDetalleCaja();
    ResultSet rs;
    DecimalFormat formateador14 = new DecimalFormat("#,##0.###");
    DecimalFormat decimales = new DecimalFormat("###,###");
    Date date = new Date();
    DateFormat fecha, hora;
    String nnnn = "0", fechaActual, horaActual;
    int resta, detallecaja, idcaja, nul;

    public AperturaCaja() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setBackground(new Color(0, 0, 0, 0));
        this.setIconifiable(false);
        this.setBorder(null);

        txtSaldoApertura.requestFocus(true);
        txtSaldoAnterior.setText(String.valueOf(cargarSaldoAnterior()));

        if (txtSaldoAnterior.getText().length() > 3) {
            String cadena = txtSaldoAnterior.getText().replace(".", "");
            txtSaldoAnterior.setText(formateador14.format(Integer.parseInt(cadena)));
        }
        fechaHora();
        botonesTransparentes();
        txtFecha.setText(fechaActual);
        txtHora.setText(horaActual);
    }
    
    public void botonesTransparentes() {
        btnGuardar.setOpaque(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setBorderPainted(false);

        btnSalir.setOpaque(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setBorderPainted(false);
    }

    private int caja() {
        String sql = "SELECT MAX(idcaja)As caja FROM caja";
        try (Connection cn = DataSource.getConnection()){
            Statement st = cn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                idcaja = rs.getInt("caja");
            }
            return idcaja;
        } catch (SQLException e) {
            return 0;
        }
    }

    public void limpiar() {
        txtSaldoApertura.setText("");
    }

    public void fechaHora() {
        fecha = new SimpleDateFormat("dd/MM/yyyy");
        fechaActual = fecha.format(date);

        hora = new SimpleDateFormat("HH:mm:ss");
        horaActual = hora.format(date);
    }

    private int cargarSaldoAnterior() {
        int saldo_anterior = 0;
        try (Connection cn = DataSource.getConnection()){
            String sql = "SELECT saldocierre FROM caja WHERE idcaja = (SELECT MAX(idcaja) FROM caja)";
            Statement st = cn.createStatement();
            rs = st.executeQuery(sql);
            if (rs.next()) {
                saldo_anterior = rs.getInt(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AperturaCaja.class.getName()).log(Level.SEVERE, null, ex);
        }
        return saldo_anterior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSaldoAnterior = new javax.swing.JTextField();
        txtSaldoApertura = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblPermisos = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setBorder(null);
        setFrameIcon(null);
        setOpaque(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Fecha:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 30, -1, -1));

        txtFecha.setEditable(false);
        txtFecha.setBackground(new java.awt.Color(255, 255, 255));
        txtFecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 27, 180, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Hora:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 69, -1, -1));

        txtHora.setEditable(false);
        txtHora.setBackground(new java.awt.Color(255, 255, 255));
        txtHora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 66, 180, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Saldo Anterior:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Saldo Apertura:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 69, -1, -1));

        txtSaldoAnterior.setEditable(false);
        txtSaldoAnterior.setBackground(new java.awt.Color(255, 255, 255));
        txtSaldoAnterior.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSaldoAnterior.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtSaldoAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 27, 180, -1));

        txtSaldoApertura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSaldoApertura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSaldoApertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoAperturaActionPerformed(evt);
            }
        });
        txtSaldoApertura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSaldoAperturaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoAperturaKeyTyped(evt);
            }
        });
        jPanel1.add(txtSaldoApertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 66, 180, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonCajaSalir.png"))); // NOI18N
        btnSalir.setToolTipText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonCajaGuardar.png"))); // NOI18N
        btnGuardar.setToolTipText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));
        jPanel1.add(lblPermisos, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 136, 33, 48));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 670, 190));

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar32.png"))); // NOI18N
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 14, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Apertura de Caja");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 280, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoAperturaCaja.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtSaldoAperturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoAperturaKeyReleased
        if (txtSaldoApertura.getText().length() > 3) {
            String cadena = txtSaldoApertura.getText().replace(".", "");
            txtSaldoApertura.setText(formateador14.format(Integer.parseInt(cadena)));
        }
    }//GEN-LAST:event_txtSaldoAperturaKeyReleased

    private void txtSaldoAperturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoAperturaKeyTyped
        String Caracteres = txtSaldoApertura.getText();
        if (Caracteres.length() >= 16) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSaldoAperturaKeyTyped

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        Principal3.lblProceso.setText("Proceso: OFF");
        this.dispose();
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void txtSaldoAperturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoAperturaActionPerformed
        guardar();
    }//GEN-LAST:event_txtSaldoAperturaActionPerformed

    //Metodos para llamar a los JDialog de Advertencia, Fallo y Realizado
    Frame f = JOptionPane.getFrameForComponent(this);
    String mensaje;

    public void advertencia() {
        Advertencia dialog = new Advertencia(f, true);
        Advertencia.lblEncabezado.setText(mensaje);
        dialog.setVisible(true);
    }

    public void fallo() {
        Fallo dialog = new Fallo(f, true);
        Fallo.lblEncabezado.setText(mensaje);
        dialog.setVisible(true);
    }

    public void realizado() {
        Realizado dialog = new Realizado(f, true);
        Realizado.lblEncabezado.setText(mensaje);
        dialog.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblFondo;
    public static javax.swing.JLabel lblPermisos;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtSaldoAnterior;
    private javax.swing.JTextField txtSaldoApertura;
    // End of variables declaration//GEN-END:variables

    public void guardar() {
        if (txtSaldoApertura.getText().isEmpty() || Integer.parseInt(txtSaldoApertura.getText().replace(".", "")) < 0) {
            mensaje = "El monto debe ser mayor a 0";
            advertencia();
        }

        datos.setFechapertura(txtFecha.getText());
        datos.setHoraapertura(txtHora.getText());
        datos.setSaldoapertura(Integer.parseInt(txtSaldoApertura.getText().replace(".", "")));
        datos.setSaldocierre(0);
        datos.setFechacierre("ABIERTO");
        datos.setHoracierre("ABIERTO");

        if (funcion.insertar(datos, funcion.buscarUsuario(Principal3.lblUsuario.getText()))) {
            caja();

            mensaje = "Caja abierta correctamente";
            realizado();

            Principal3.smnuMovimientos.setEnabled(true);
            funcion.idCaja();
            funcion.idDetalleCaja();
            Principal3.txtIdcaja.setText(String.valueOf(funcion.idCaja()));
            Principal3.txtIddetallecaja.setText(String.valueOf(funcion.idDetalleCaja()));
            Principal3.txtCaja.setText("Caja Abierta");
            Principal3.smnuAbrirCaja.setEnabled(false);
            Principal3.smnuCerrarCaja.setEnabled(true);
            Principal3.mnuCompras.setEnabled(true);
            Principal3.mnuVentas.setEnabled(true);

            String usuario = Principal3.lblUsuario.getText();
            String objeto = txtSaldoApertura.getText();
            String Accion = "APERTURA";
//            audi.audiclientes(usuario, objeto, Accion);

            dispose();
        } else {
            mensaje = "Error al abrir la caja";
            fallo();
        }
    }
}
