package View.Caja;

import Config.DataSource;
import View.Principal3;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author SwichBlade15
 */
public final class MovimientosCaja1 extends javax.swing.JInternalFrame {

    ResultSet st;
    Date date = new Date();
    DateFormat hora, fecha;
    String fechaActual, horaActual;
    int ingresodia, egresodia;

    public MovimientosCaja1() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setBackground(new Color(0, 0, 0, 0));
        this.setIconifiable(false);
        this.setBorder(null);
        
        fechaHora();
        movimiento();
//        diferencia();
    }

    public void fechaHora() {
        fecha = new SimpleDateFormat("dd/MM/yyyy");
        fechaActual = fecha.format(date);
    }

    public void movimiento() {
        try (Connection cn = DataSource.getConnection()){
            PreparedStatement ps = cn.prepareStatement("SELECT ingresodia, egresodia FROM caja WHERE fechaapertura = ? AND fechacierre = ?");
            ps.setString(1, fechaActual);
            ps.setString(2, "ABIERTO");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                ingresodia = rs.getInt("ingresodia");
                egresodia = rs.getInt("egresodia");
            }
//            txtIngresodia.setText(String.valueOf(ingresodia));
//            txtEgresodia.setText(String.valueOf(egresodia));
        } catch (SQLException e) {
        }
    }
    
//    public void diferencia(){
//        int ingre = Integer.parseInt(txtIngresodia.getText());
//        int egre = Integer.parseInt(txtEgresodia.getText());
//        int resta;
//        resta = ingre-egre;
//        
//        txtDiferencia.setText(String.valueOf(resta));
//        
//        if(ingre>egre){
//            txtDiferencia.setBackground(new Color(204,255,204));
//        }else{
//            txtDiferencia.setBackground(new Color(255,229,229));
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCerrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setOpaque(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar32.png"))); // NOI18N
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 14, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Movimiento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 220, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        Principal3.lblProceso.setText("Proceso: OFF");
        this.dispose();
    }//GEN-LAST:event_lblCerrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCerrar;
    // End of variables declaration//GEN-END:variables
}
