package View.Products;

import Config.DataSource;
import Controller.FuncionesProductos;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author SwichBlade15
 */
public final class SeleccionarProductosBaja extends javax.swing.JInternalFrame {

    FuncionesProductos funcion = new FuncionesProductos();
    private String sSQL = "";
    public Integer totalRegistros;
    ResultSet rs;
    Statement st;
    PreparedStatement ps;
    String busqueda = "";
    DefaultTableModel model;

    public SeleccionarProductosBaja() {
        initComponents();
        llenarTabla("");
    }

    void llenarTabla(String buscar) {
        try (Connection cn = DataSource.getConnection()){
            String[] titulos = {"ID", "Codigo", "Productos", "F. Compra", "F. Venc."};
            model = new DefaultTableModel(null, titulos);
            sSQL = "SELECT productos.idproductos, productos.productos, productos.codigo, productos.fechavencimiento, "
                    + "compras.fecha FROM productos"
                    + "LEFT OUTER JOIN detallecompra ON productos.idproductos = detallecompra.fk_productos "
                    + "LEFT OUTER JOIN compras ON detallecompra.fk_compras = compras.idcompras ";

            switch (busqueda) {
                default:
                    st = cn.createStatement();
                    rs = st.executeQuery(sSQL);
                    break;
                case "codigo":
                    sSQL = sSQL + " WHERE codigo = ?";
                    ps = cn.prepareStatement(sSQL);
                    ps.setString(1, buscar);
                    rs = ps.executeQuery();
                    break;
                case "productos":
                    sSQL = sSQL + " WHERE productos = ?";
                    ps = cn.prepareStatement(sSQL);
                    ps.setString(1, buscar);
                    rs = ps.executeQuery();
                    break;
            }

            String[] fila = new String[3];
            while (rs.next()) {
                fila[0] = rs.getString("idproductos");
                fila[1] = rs.getString("codigo");
                fila[2] = rs.getString("productos");
                fila[3] = rs.getString("fechavencimiento");
                fila[4] = rs.getString("fecha");
                
                model.addRow(fila);
            }
            tblSeleccionar.setModel(model);

            JTableHeader th;
            th = tblSeleccionar.getTableHeader();
            Font fuente = new Font("Tahoma", Font.BOLD, 14);
            th.setFont(fuente);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void ocultar_columnas() {
        tblSeleccionar.getColumnModel().getColumn(0).setMaxWidth(0);
        tblSeleccionar.getColumnModel().getColumn(0).setMinWidth(0);
        tblSeleccionar.getColumnModel().getColumn(0).setPreferredWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtProductos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSeleccionar = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel1.setText("Seleccionar Producto");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Codigo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Producto:");

        txtCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCodigoMouseClicked(evt);
            }
        });
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        txtProductos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtProductosMouseClicked(evt);
            }
        });
        txtProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductosActionPerformed(evt);
            }
        });
        txtProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProductosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProductosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProductosKeyTyped(evt);
            }
        });

        tblSeleccionar = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        tblSeleccionar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblSeleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSeleccionarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSeleccionar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(txtCodigo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProductos)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased

    }//GEN-LAST:event_txtCodigoKeyReleased

    private void txtProductosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductosKeyReleased
        llenarTabla(txtProductos.getText());
    }//GEN-LAST:event_txtProductosKeyReleased

    private void txtCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoMouseClicked
        busqueda = "codigo";
    }//GEN-LAST:event_txtCodigoMouseClicked

    private void txtProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProductosMouseClicked
        busqueda = "productos";
    }//GEN-LAST:event_txtProductosMouseClicked

    private void txtProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductosActionPerformed

    }//GEN-LAST:event_txtProductosActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed

    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
//        if(evt.getKeyChar()==KeyEvent.VK_ENTER){
//            llenarTabla(txtCodigo.getText());
//        }else{
//            
//        }
    }//GEN-LAST:event_txtCodigoKeyPressed

    private void txtProductosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductosKeyPressed
//        if(evt.getKeyChar()==KeyEvent.VK_ENTER){
//            llenarTabla(txtProductos.getText());
//        }else{
//            
//        }
    }//GEN-LAST:event_txtProductosKeyPressed

    private void txtProductosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductosKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
//        
//        if(evt.getKeyChar()==KeyEvent.VK_ENTER){
//            llenarTabla(txtProductos.getText());
//        }else{
//            
//        }
    }//GEN-LAST:event_txtProductosKeyTyped

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }

        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            llenarTabla(txtCodigo.getText());
        } else {

        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void tblSeleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSeleccionarMouseClicked
        int seleccionar = tblSeleccionar.rowAtPoint(evt.getPoint());

        if (evt.getClickCount() == 2) {

        }
    }//GEN-LAST:event_tblSeleccionarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSeleccionar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtProductos;
    // End of variables declaration//GEN-END:variables
}
